### ISSUE TITLE
[20.8.1] webui unable to handle certain states

### ISSUE THREAD

**Issue by pomac303** [greenbone/gsa#2768]
### Expected behavior

To see the reports

### Actual behavior

TypeError: Cannot read property 'scan_run_status' of undefined

in hG
    in tbody
    in t
    in styled.tbody
    in table
    in Unknown
    in t
    in Styled(StripedTable)
    in div
    in Unknown
    in t
    in Styled(Layout)
    in n
    in Unknown
    in div
    in Unknown
    in t
    in Layout
    in section
    in tr
    in n
    in div
    in Unknown
    in t
    in Layout
    in n
    in w
    in Unknown
    in n
    in n
    in w
    in withRouter(Connect(n))
    in n
    in Unknown
    in l
    in w
    in Unknown
    in a
    in n
    in Unknown
    in Tg
    in n
    in Unknown
    in w
    in Unknown
    in t
    in t
    in n
    in main
    in t
    in Main
    in Unknown
    in t
    in withLayout(Main)
    in div
    in Unknown
    in t
    in Styled(Layout)
    in n
    in withRouter(n)
    in Unknown
    in n
    in w
    in withRouter(Connect(n))
    in Unknown
    in n
    in w
    in withRouter(Connect(n))
    in Unknown
    in t
    in t
    in Unknown
    in Unknown
    in n
    in w
    in l
    in n
    in n
TypeError: Cannot read property 'scan_run_status' of undefined
    at hG (http://10.129.5.118:8080/static/js/main.7344b28e.chunk.js:1:1452780)
    at Gi (http://10.129.5.118:8080/static/js/2.874e4989.chunk.js:2:684338)
    at bc (http://10.129.5.118:8080/static/js/2.874e4989.chunk.js:2:730750)
    at us (http://10.129.5.118:8080/static/js/2.874e4989.chunk.js:2:723277)
    at cs (http://10.129.5.118:8080/static/js/2.874e4989.chunk.js:2:723202)
    at Zc (http://10.129.5.118:8080/static/js/2.874e4989.chunk.js:2:720211)
    at http://10.129.5.118:8080/static/js/2.874e4989.chunk.js:2:671596
    at t.unstable_runWithPriority (http://10.129.5.118:8080/static/js/2.874e4989.chunk.js:2:747183)
    at Yo (http://10.129.5.118:8080/static/js/2.874e4989.chunk.js:2:671305)
    at Vo (http://10.129.5.118:8080/static/js/2.874e4989.chunk.js:2:671541)

### Steps to reproduce

Unknown, but there seems to be no real way out of this error state

### GVM versions

20.8.1

### Environment

**Operating system:**

Ubuntu 20.04 with 5.11 kernel

**Installation method / source:** (packages, source installation)

https://launchpad.net/~mrazavi/+archive/ubuntu/gvm

Deployed with:
https://github.com/admirito/gvm-containers

With small modifications to the containers themselves

**Comment by y0urself** [comment]
This should have been fixed with 20.8.6 ... https://github.com/greenbone/gsa/issues/2389
