### ISSUE TITLE
[gsa-7.0] error during the make process

### ISSUE THREAD

**Issue by JustMe213** [greenbone/gsa#464]
During the make process I got the following error

Traceback (most recent call last):
  File "/openvas/update/gsa/tools/po2json", line 66, in <module>
    main()
  File "/openvas/update/gsa/tools/po2json", line 62, in main
    convert(sys.argv[1], sys.argv[2])
  File "/openvas/update/gsa/tools/po2json", line 45, in convert
    po_f = polib.pofile(in_name)
  File "/usr/local/lib/python2.7/dist-packages/polib.py", line 138, in pofile
    return _pofile_or_mofile(pofile, 'pofile', **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/polib.py", line 86, in _pofile_or_mofile
    instance = parser.parse()
  File "/usr/local/lib/python2.7/dist-packages/polib.py", line 1320, in parse
    self.process(keywords[tokens[0]])
  File "/usr/local/lib/python2.7/dist-packages/polib.py", line 1464, in process
    self.current_line)
IOError: Syntax error in po file (line 430)
src/po/CMakeFiles/gettext-json.dir/build.make:74: recipe for target 'src/po/gsad-fr.json' failed
make[2]: *** [src/po/gsad-fr.json] Error 1
CMakeFiles/Makefile2:1020: recipe for target 'src/po/CMakeFiles/gettext-json.dir/all' failed
make[1]: *** [src/po/CMakeFiles/gettext-json.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

How to fix it.

In the https://github.com/greenbone/gsa/blob/gsa-7.0/src/po/gsad_js-fr.po line 430 you need to have msgstr instead of msgid

( Ubuntu 16.04.4 LTS, build from source)

**Comment by bjoernricks** [comment]
Should be fixed with #493
