### ISSUE TITLE
[7.0.3] Build fails with po file error

### ISSUE THREAD

**Issue by tuxmaster** [greenbone/gsa#498]
The 7.0.3 build fails with:

> [ 68%] Generating gsad-ru.json
> cd /builddir/build/BUILD/gsa-7.0.3/src/po && /usr/bin/msgfmt /builddir/build/BUILD/gsa-7.0.3/src/po/gsad_xsl-de.po -o /builddir/build/BUILD/gsa-7.0.3/src/po/de/gsad_xsl.mo
> cd /builddir/build/BUILD/gsa-7.0.3/src/po && /usr/bin/python /builddir/build/BUILD/gsa-7.0.3/tools/po2json /builddir/build/BUILD/gsa-7.0.3/src/po/gsad_js-ru.po /builddir/build/BUILD/gsa-7.0.3/src/po/gsad-ru.json
> Traceback (most recent call last):
>   File "/builddir/build/BUILD/gsa-7.0.3/tools/po2json", line 66, in <module>
>     main()
>   File "/builddir/build/BUILD/gsa-7.0.3/tools/po2json", line 62, in main
>     convert(sys.argv[1], sys.argv[2])
>   File "/builddir/build/BUILD/gsa-7.0.3/tools/po2json", line 45, in convert
>     po_f = polib.pofile(in_name)
>   File "/usr/lib/python2.7/site-packages/polib.py", line 138, in pofile
>     return _pofile_or_mofile(pofile, 'pofile', **kwargs)
>   File "/usr/lib/python2.7/site-packages/polib.py", line 86, in _pofile_or_mofile
>     instance = parser.parse()
>   File "/usr/lib/python2.7/site-packages/polib.py", line 1306, in parse
>     self.process(keywords[tokens[0]])
>   File "/usr/lib/python2.7/site-packages/polib.py", line 1450, in process
>     self.current_line)
> IOError: Syntax error in po file (line 430)

**Comment by rgrewe** [comment]
It seems tuxmaster has problems with gsad-ru.po not gsad.fr.po.

**Comment by cfi-gb** [comment]
The gsad-fr.po should be mentioned after the last "IOError: Syntax error in po file (line 430)" like shown in the pasted output in https://github.com/greenbone/gsa/pull/493

**Comment by tuxmaster** [comment]
It will fix also my problem.
